"""rename user to users

Revision ID: 0384fdfc15de
Revises: 87ee087c5000
Create Date: 2026-05-24 22:11:54.034735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0384fdfc15de'
down_revision: Union[str, Sequence[str], None] = '87ee087c5000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("user", "users")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("users", "user")

    # ### end Alembic commands ###
