"""Create users table

Revision ID: 87ee087c5000
Revises: 
Create Date: 2026-05-13 11:06:25.302900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87ee087c5000'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_referrals')
    op.drop_index(op.f('ix_agent_agent_code'), table_name='agent')
    op.drop_index(op.f('ix_agent_agent_phone'), table_name='agent')
    op.drop_table('agent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agent_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('agent_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('agent_phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('agent_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_pkey'))
    )
    op.create_index(op.f('ix_agent_agent_phone'), 'agent', ['agent_phone'], unique=True)
    op.create_index(op.f('ix_agent_agent_code'), 'agent', ['agent_code'], unique=False)
    op.create_table('agent_referrals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], name=op.f('agent_referrals_agent_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('agent_referrals_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_referrals_pkey'))
    )
    # ### end Alembic commands ###
